{{
    config(
        materialized = 'incremental',
        unique_key = ['ASSIGNMENT_NAME','ASSIGNMENT_EMPLOYMENT_CATEGORY','ASSIGNMENT_CURRENT_CHG_ACTION',
'ASSIGNMENT_CURRENT_CHG_REASON','ASSIGNMENT_STATUS','HOURLY_SALARIED','GRADE_NAME','Assignment_Current_Effective_Date']
    )
}}

WITH assign AS(
    SELECT distinct ASSIGNMENT_NAME, ASSIGNMENT_EMPLOYMENT_CATEGORY, 
    ASSIGNMENT_CURRENT_CHG_ACTION, ASSIGNMENT_CURRENT_CHG_REASON, 
    ASSIGNMENT_STATUS, HOURLY_SALARIED, GRADE_NAME,Assignment_Current_Effective_Date
 FROM {{ref("src_active_join_learning")}}
)
SELECT *,{{dbt_utils.generate_surrogate_key(['ASSIGNMENT_NAME','ASSIGNMENT_EMPLOYMENT_CATEGORY','ASSIGNMENT_CURRENT_CHG_ACTION',
'ASSIGNMENT_CURRENT_CHG_REASON','ASSIGNMENT_STATUS','HOURLY_SALARIED','GRADE_NAME','Assignment_Current_Effective_Date'])}} AS assig_id
 FROM assign

-- SELECT *,ROW_NUMBER()OVER( ORDER BY ASSIGNMENT_NAME, ASSIGNMENT_EMPLOYMENT_CATEGORY, 
--     ASSIGNMENT_CURRENT_CHG_ACTION, ASSIGNMENT_CURRENT_CHG_REASON, 
--     ASSIGNMENT_STATUS, HOURLY_SALARIED, GRADE_NAME,Assignment_Current_Effective_Date ) AS assig_id 
--  FROM assign